trigger:
- master

pr: none

pool:
  name: Contabo
steps:

- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Docker Hub'
    repository: configcat/docs
    command: build
    Dockerfile: Dockerfile
    buildContext: '$(System.DefaultWorkingDirectory)'
    arguments: '--build-arg SONAR_TOKEN=75c6762b139ff0d46d6f71efe6933d9b63b3da31 --network=host'

- task: Docker@2
  displayName: push
  inputs:
    containerRegistry: 'Docker Hub'
    repository: configcat/docs
    command: push
